"""
FastAPI backend for object detection inference.
Serves YOLOv8 and RT-DETR models with PyTorch, ONNX, and TensorRT backends.

Run on Colab: uvicorn main:app --host 0.0.0.0 --port 8000
Or locally:   uvicorn main:app --reload --port 8000
"""

import time
import json
import tempfile
from pathlib import Path

import cv2
import numpy as np
from fastapi import FastAPI, File, UploadFile, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from ultralytics import YOLO

app = FastAPI(title="Object Detection API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Load models at startup from model_paths.json (generated by 01_model_export notebook)
models = {}
model_paths = {}

MODEL_PATHS_FILE = Path("model_paths.json")
if MODEL_PATHS_FILE.exists():
    with open(MODEL_PATHS_FILE) as f:
        model_paths = json.load(f)
    for key, path in model_paths.items():
        if Path(path).exists():
            print(f"Loading {key} from {path}...")
            models[key] = YOLO(path)
        else:
            print(f"Skipping {key} — file not found: {path}")
    print(f"\nLoaded {len(models)} models: {list(models.keys())}")
else:
    print("WARNING: model_paths.json not found. Run the export notebook first.")


@app.get("/health")
def health():
    return {"status": "ok", "models_loaded": list(models.keys())}


@app.get("/models")
def list_models():
    return {
        "models": [
            {"key": key, "path": model_paths.get(key, "")}
            for key in models
        ]
    }


@app.post("/detect")
async def detect(
    file: UploadFile = File(...),
    model: str = Query(default="yolov8m_pytorch", description="Model key from /models"),
    confidence: float = Query(default=0.25, ge=0.0, le=1.0),
):
    if model not in models:
        return JSONResponse(
            status_code=400,
            content={"error": f"Unknown model: {model}. Available: {list(models.keys())}"},
        )

    contents = await file.read()
    img_array = np.frombuffer(contents, np.uint8)
    img = cv2.imdecode(img_array, cv2.IMREAD_COLOR)
    if img is None:
        return JSONResponse(status_code=400, content={"error": "Could not decode image"})

    start = time.perf_counter()
    results = models[model](img, conf=confidence, verbose=False)
    latency_ms = (time.perf_counter() - start) * 1000

    detections = []
    for box in results[0].boxes:
        x1, y1, x2, y2 = box.xyxy[0].tolist()
        detections.append({
            "bbox": [round(x1, 1), round(y1, 1), round(x2, 1), round(y2, 1)],
            "confidence": round(float(box.conf[0]), 3),
            "class_id": int(box.cls[0]),
            "class_name": results[0].names[int(box.cls[0])],
        })

    return {
        "detections": detections,
        "model": model,
        "latency_ms": round(latency_ms, 1),
        "image_size": {"width": img.shape[1], "height": img.shape[0]},
    }


@app.post("/detect-video")
async def detect_video(
    file: UploadFile = File(...),
    model: str = Query(default="yolov8m_pytorch"),
    confidence: float = Query(default=0.25, ge=0.0, le=1.0),
    max_frames: int = Query(default=30, ge=1, le=300),
):
    if model not in models:
        return JSONResponse(status_code=400, content={"error": f"Unknown model: {model}"})

    with tempfile.NamedTemporaryFile(suffix=".mp4", delete=False) as tmp:
        tmp.write(await file.read())
        tmp_path = tmp.name

    cap = cv2.VideoCapture(tmp_path)
    fps = cap.get(cv2.CAP_PROP_FPS) or 30
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    frames_results = []
    frame_idx = 0
    total_latency = 0

    while cap.isOpened() and frame_idx < max_frames:
        ret, frame = cap.read()
        if not ret:
            break

        start = time.perf_counter()
        results = models[model](frame, conf=confidence, verbose=False)
        latency_ms = (time.perf_counter() - start) * 1000
        total_latency += latency_ms

        detections = []
        for box in results[0].boxes:
            x1, y1, x2, y2 = box.xyxy[0].tolist()
            detections.append({
                "bbox": [round(x1, 1), round(y1, 1), round(x2, 1), round(y2, 1)],
                "confidence": round(float(box.conf[0]), 3),
                "class_id": int(box.cls[0]),
                "class_name": results[0].names[int(box.cls[0])],
            })

        frames_results.append({
            "frame": frame_idx,
            "detections": detections,
            "latency_ms": round(latency_ms, 1),
        })
        frame_idx += 1

    cap.release()
    Path(tmp_path).unlink(missing_ok=True)

    return {
        "frames": frames_results,
        "model": model,
        "video_fps": round(fps, 1),
        "total_frames_processed": frame_idx,
        "total_frames_in_video": total_frames,
        "avg_latency_ms": round(total_latency / max(frame_idx, 1), 1),
    }
